-- Real editorial content for the two CMS pages the backoffice can now
-- override on the public site (see frontend faq/page.tsx and
-- app/[locale]/(site)/page.tsx): the FAQ's 9 real Q&As in their 3
-- existing categories, and the homepage's "Comment ça marche"/"Book
-- direct" sections. Every string below is copied verbatim from the
-- already-live frontend/messages/*.json translations that shipped this
-- content originally - nothing invented, just migrated so the business
-- owner can edit it from the backoffice from now on. PUBLISHED
-- immediately: this is a straight copy of what's already live, not new
-- unreviewed content, so there is no draft period to gate it behind.

-- FAQ — FR
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'Tout ce qu''il faut savoir avant de réserver', 'faq', 'FR', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'richText', '{"heading":"Réservation et annulation","content":""}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'faq', '{"question":"Quelle est la politique d''annulation ?","answer":"Plus de 24 heures avant le départ : aucun frais. Dans les 24 heures : 50 % du prix du séjour. En cas d''absence à l''entrée : prix intégral. Si l''annulation vient de nous — météo, matériel ou tout autre motif de notre fait — vous choisissez entre un remboursement intégral ou une reprogrammation gratuite."}', 1);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'faq', '{"question":"Dois-je payer au moment de la réservation ?","answer":"Non. Rien n''est débité au moment de la réservation — le paiement se fait à la porte ou par lien sécurisé."}', 2);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'faq', '{"question":"Que se passe-t-il si le temps se dégrade le jour de mon séjour ?","answer":"Les tempêtes de sable et le vent fort signifient une annulation, avec remboursement complet ou reprogrammation gratuite. Cette décision est prise par le guide en chef, jamais par le bureau des réservations."}', 3);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'richText', '{"heading":"Informations pratiques","content":""}', 4);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'faq', '{"question":"Que dois-je porter et emporter ?","answer":"Des chaussures fermées, des manches longues et des lunettes de soleil pour la journée ; une couche chaude pour la soirée, les nuits dans le désert étant fraîches même quand les journées sont chaudes. Nous distribuons un chèche pour la tête et le cou à la porte."}', 5);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'faq', '{"question":"Y a-t-il du réseau téléphonique à Sabria ?","answer":"Par intermittence seulement. Chaque guide porte un messager satellite et une radio chargée, et la base à la porte connaît chaque itinéraire et l''heure de retour prévue."}', 6);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'faq', '{"question":"Pouvez-vous gérer des besoins alimentaires ou médicaux particuliers ?","answer":"Oui — dites-le-nous lors de la réservation. Nous proposons des options végétariennes, végétaliennes et sans gluten au campement, et nos guides sont informés de toute condition que vous nous communiquez."}', 7);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'richText', '{"heading":"Âge et participation","content":""}', 8);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'faq', '{"question":"Faut-il de l''expérience pour conduire un quad ?","answer":"Non. Les quads sont automatiques et chaque session commence par un briefing et un tour d''essai sur le plat avant de partir dans les dunes. Les conducteurs doivent avoir 16 ans ou plus et présenter une pièce d''identité avec photo."}', 9);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'faq', '{"question":"La randonnée à dos de chameau convient-elle aux enfants ?","answer":"Les enfants à partir de six ans peuvent monter avec un parent, un chamelier marchant aux côtés de chaque chameau tout le long du parcours. En dessous de six ans, nous recommandons plutôt la visite du campement au coucher du soleil."}', 10);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('123d965a-ac03-4021-b3ed-261968dec89d', 'faq', '{"question":"Que se passe-t-il en cas de grossesse ou de besoin de mobilité particulier ?","answer":"Signalez-le-nous lors de la réservation : nous préférons vous orienter vers le bon séjour plutôt que de vous refuser l''accès à l''entrée."}', 11);

-- Home — FR
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('1b0d6395-e63b-4e9a-bd4a-e966fa8872d9', 'Accueil', 'home', 'FR', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('1b0d6395-e63b-4e9a-bd4a-e966fa8872d9', 'steps', '{"eyebrow":"Comment ça marche","items":[{"title":"Choisissez votre aventure","body":"Optez pour une seule activité ou combinez chameau, quad et planche en une seule expédition au coucher du soleil."},{"title":"Réservez votre créneau","body":"Réservez un créneau du matin ou de l''heure dorée. Équipement, guides et transferts sont tous inclus."},{"title":"Rendez-vous à la porte","body":"Arrivez à la porte de Sabria, rencontrez votre guide, et partez à travers le Sahara à ciel ouvert."}]}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('1b0d6395-e63b-4e9a-bd4a-e966fa8872d9', 'bookDirect', '{"eyebrow":"Réserver en direct","lead":"Nous organisons nous-mêmes chaque sortie de cette page. Réserver ici signifie qu''aucune plateforme ne prend de commission — l''économie vous revient, et vos questions arrivent directement aux personnes qui vous attendront à la porte.","ctaLabel":"Réserver en direct maintenant","headingHere":"Directement avec Dunes Insolites","advantages":[{"text":"Meilleur prix — aucune commission de plateforme en plus"},{"text":"Parlez au guide qui mène votre sortie, pas à un centre d''appels"},{"text":"Annulation gratuite jusqu''à 24 heures avant"},{"text":"Paiement à la porte — rien n''est débité pour réserver"},{"text":"Prise en charge flexible depuis votre hôtel à Douz ou Kébili"},{"text":"Vos photos et vidéos envoyées le lendemain matin"}]}', 1);

-- FAQ — EN
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'Everything worth knowing before you book', 'faq', 'EN', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'richText', '{"heading":"Booking and cancellation","content":""}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'faq', '{"question":"What''s the cancellation policy?","answer":"More than 24 hours before departure: no charge. Within 24 hours: 50% of the trip price. No-show at the gate: full price. If we''re the ones cancelling — weather, equipment, or any reason on our side — you choose between a full refund or a free reschedule."}', 1);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'faq', '{"question":"Do I pay when I book?","answer":"No. Nothing is charged at booking time — payment is taken at the gate or through a secure link."}', 2);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'faq', '{"question":"What happens if the weather turns on the day of my trip?","answer":"Sandstorms and strong wind mean cancellation, with a full refund or a free reschedule. That call is made by the head guide, never by the booking office."}', 3);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'richText', '{"heading":"Practical information","content":""}', 4);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'faq', '{"question":"What should I wear and bring?","answer":"Closed shoes, long sleeves, and sunglasses for the day; a warm layer for the evening, since desert nights are cool even after a hot day. We hand out a chèche (head and neck scarf) at the gate."}', 5);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'faq', '{"question":"Is there phone signal in Sabria?","answer":"Intermittent at best. Every guide carries a charged satellite messenger and radio, and the base at the gate knows every route and expected return time."}', 6);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'faq', '{"question":"Can you handle dietary or medical needs?","answer":"Yes — tell us when you book. We offer vegetarian, vegan, and gluten-free options at the camp, and our guides are briefed on any condition you tell us about."}', 7);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'richText', '{"heading":"Age and participation","content":""}', 8);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'faq', '{"question":"Do I need experience to drive a quad?","answer":"No. The quads are automatic, and every session starts with a briefing and a practice lap on flat ground before heading into the dunes. Drivers must be 16 or older with photo ID."}', 9);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'faq', '{"question":"Is the camel trek suitable for children?","answer":"Children aged six and up can ride with a parent, with a camel handler walking alongside each camel the whole way. Under six, we recommend the sunset camp visit instead."}', 10);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('8afc30fe-f68e-4e7d-a487-c36d861ef743', 'faq', '{"question":"What about pregnancy or a mobility need?","answer":"Tell us when you book — we''d much rather point you to the right trip than turn you away at the gate."}', 11);

-- Home — EN
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('cddd911b-e293-4d03-b9f0-74a578ee0ce2', 'Home', 'home', 'EN', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('cddd911b-e293-4d03-b9f0-74a578ee0ce2', 'steps', '{"eyebrow":"How it works","items":[{"title":"Pick your adventure","body":"Choose a single activity or bundle camel, quad, and board into one sunset expedition."},{"title":"Book your window","body":"Reserve a morning or golden-hour slot. Gear, guides, and transfers are all included."},{"title":"Meet at the gate","body":"Arrive at the Sabria gate, meet your guide, and head out across the open Sahara."}]}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('cddd911b-e293-4d03-b9f0-74a578ee0ce2', 'bookDirect', '{"eyebrow":"Book direct","lead":"We run every trip on this page ourselves. Booking here means no platform takes a cut — so the saving goes to you, and your questions come straight to the people who will be standing at the gate.","ctaLabel":"Book direct now","headingHere":"Direct with Dunes Insolites","advantages":[{"text":"Best price — no platform commission on top"},{"text":"Talk to the guide who runs your trip, not a call centre"},{"text":"Free cancellation up to 24 hours before"},{"text":"Pay at the gate — nothing charged to book"},{"text":"Flexible pickup from your hotel in Douz or Kebili"},{"text":"Your photos and video sent the next morning"}]}', 1);

-- FAQ — DE
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'Alles Wissenswerte vor der Buchung', 'faq', 'DE', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'richText', '{"heading":"Buchung und Stornierung","content":""}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'faq', '{"question":"Wie lautet die Stornierungsrichtlinie?","answer":"Mehr als 24 Stunden vor der Abreise: keine Kosten. Innerhalb von 24 Stunden: 50 % des Reisepreises. Nichterscheinen am Tor: voller Preis. Wenn wir stornieren — Wetter, Ausrüstung oder ein anderer Grund unsererseits — können Sie zwischen voller Rückerstattung oder kostenloser Umbuchung wählen."}', 1);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'faq', '{"question":"Muss ich bei der Buchung bezahlen?","answer":"Nein. Bei der Buchung wird nichts abgebucht — die Zahlung erfolgt am Tor oder über einen sicheren Link."}', 2);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'faq', '{"question":"Was passiert, wenn sich das Wetter am Tag meines Ausflugs verschlechtert?","answer":"Sandstürme und starker Wind bedeuten eine Stornierung, mit voller Rückerstattung oder kostenloser Umbuchung. Diese Entscheidung trifft der Chefguide, niemals das Buchungsbüro."}', 3);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'richText', '{"heading":"Praktische Informationen","content":""}', 4);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'faq', '{"question":"Was soll ich anziehen und mitbringen?","answer":"Geschlossene Schuhe, lange Ärmel und eine Sonnenbrille für den Tag; eine warme Schicht für den Abend, da die Wüstennächte kühl sind, selbst nach einem heißen Tag. Wir verteilen am Tor einen Chèche (Kopf- und Halstuch)."}', 5);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'faq', '{"question":"Gibt es in Sabria Handyempfang?","answer":"Bestenfalls unregelmäßig. Jeder Guide trägt einen geladenen Satellitenmessenger und ein Funkgerät, und die Basis am Tor kennt jede Route und die erwartete Rückkehrzeit."}', 6);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'faq', '{"question":"Könnt ihr auf Ernährungs- oder medizinische Bedürfnisse eingehen?","answer":"Ja — sagen Sie es uns bei der Buchung. Wir bieten vegetarische, vegane und glutenfreie Optionen im Camp an, und unsere Guides werden über jede Erkrankung informiert, die Sie uns mitteilen."}', 7);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'richText', '{"heading":"Alter und Teilnahme","content":""}', 8);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'faq', '{"question":"Braucht man Erfahrung, um ein Quad zu fahren?","answer":"Nein. Die Quads sind automatisch, und jede Session beginnt mit einer Einweisung und einer Proberunde auf ebenem Gelände, bevor es in die Dünen geht. Fahrer müssen mindestens 16 Jahre alt sein und einen Lichtbildausweis vorlegen."}', 9);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'faq', '{"question":"Ist der Kamelritt für Kinder geeignet?","answer":"Kinder ab sechs Jahren können mit einem Elternteil reiten, wobei ein Kamelführer den ganzen Weg neben jedem Kamel hergeht. Unter sechs Jahren empfehlen wir stattdessen den Sonnenuntergangsbesuch im Camp."}', 10);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('f6958a7f-db57-4195-a4e4-7d050a44bddc', 'faq', '{"question":"Was ist bei Schwangerschaft oder besonderem Mobilitätsbedarf?","answer":"Sagen Sie es uns bei der Buchung — wir weisen Sie lieber auf den richtigen Ausflug hin, als Sie am Tor abzuweisen."}', 11);

-- Home — DE
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('885e9f4a-1a6b-4ee1-9037-6f33e44587ae', 'Startseite', 'home', 'DE', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('885e9f4a-1a6b-4ee1-9037-6f33e44587ae', 'steps', '{"eyebrow":"So funktioniert''s","items":[{"title":"Wählen Sie Ihr Abenteuer","body":"Wählen Sie eine einzelne Aktivität oder kombinieren Sie Kamel, Quad und Board zu einer Sonnenuntergangs-Expedition."},{"title":"Buchen Sie Ihr Zeitfenster","body":"Reservieren Sie einen Morgen- oder Golden-Hour-Slot. Ausrüstung, Guides und Transfers sind alle inklusive."},{"title":"Treffpunkt am Tor","body":"Kommen Sie zum Tor von Sabria, treffen Sie Ihren Guide und brechen Sie auf in die offene Sahara."}]}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('885e9f4a-1a6b-4ee1-9037-6f33e44587ae', 'bookDirect', '{"eyebrow":"Direkt buchen","lead":"Wir führen jede Tour auf dieser Seite selbst durch. Eine Buchung hier bedeutet, dass keine Plattform eine Provision einbehält — die Ersparnis geht an Sie, und Ihre Fragen erreichen direkt die Menschen, die am Tor auf Sie warten werden.","ctaLabel":"Jetzt direkt buchen","headingHere":"Direkt bei Dunes Insolites","advantages":[{"text":"Bester Preis — keine zusätzliche Plattformprovision"},{"text":"Sprechen Sie mit dem Guide, der Ihre Tour leitet, nicht mit einem Callcenter"},{"text":"Kostenlose Stornierung bis 24 Stunden vorher"},{"text":"Zahlung am Tor — bei der Buchung wird nichts abgebucht"},{"text":"Flexible Abholung von Ihrem Hotel in Douz oder Kebili"},{"text":"Ihre Fotos und Videos werden am nächsten Morgen zugesandt"}]}', 1);

-- FAQ — IT
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'Tutto quello che serve sapere prima di prenotare', 'faq', 'IT', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'richText', '{"heading":"Prenotazione e cancellazione","content":""}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'faq', '{"question":"Qual è la politica di cancellazione?","answer":"Più di 24 ore prima della partenza: nessun costo. Entro 24 ore: 50% del prezzo del soggiorno. Mancata presentazione all''ingresso: prezzo intero. Se siamo noi ad annullare — meteo, attrezzatura o qualsiasi altro motivo a nostro carico — potete scegliere tra un rimborso completo o una riprogrammazione gratuita."}', 1);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'faq', '{"question":"Devo pagare al momento della prenotazione?","answer":"No. Non viene addebitato nulla al momento della prenotazione — il pagamento avviene all''ingresso o tramite link sicuro."}', 2);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'faq', '{"question":"Cosa succede se il tempo peggiora il giorno della mia escursione?","answer":"Tempeste di sabbia e vento forte comportano l''annullamento, con rimborso completo o riprogrammazione gratuita. Questa decisione spetta alla guida capo, mai all''ufficio prenotazioni."}', 3);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'richText', '{"heading":"Informazioni pratiche","content":""}', 4);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'faq', '{"question":"Cosa devo indossare e portare?","answer":"Scarpe chiuse, maniche lunghe e occhiali da sole per il giorno; uno strato caldo per la sera, poiché le notti nel deserto sono fresche anche dopo una giornata calda. Distribuiamo uno chèche (sciarpa per testa e collo) all''ingresso."}', 5);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'faq', '{"question":"C''è copertura telefonica a Sabria?","answer":"Solo a intermittenza. Ogni guida porta un messaggero satellitare carico e una radio, e la base all''ingresso conosce ogni percorso e l''orario di rientro previsto."}', 6);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'faq', '{"question":"Potete gestire esigenze alimentari o mediche?","answer":"Sì — comunicatecelo al momento della prenotazione. Offriamo opzioni vegetariane, vegane e senza glutine al campo, e le nostre guide sono informate su qualsiasi condizione che ci comunichiate."}', 7);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'richText', '{"heading":"Età e partecipazione","content":""}', 8);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'faq', '{"question":"Serve esperienza per guidare un quad?","answer":"No. I quad sono automatici, e ogni sessione inizia con un briefing e un giro di prova su terreno pianeggiante prima di partire verso le dune. I conducenti devono avere almeno 16 anni e presentare un documento con foto."}', 9);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'faq', '{"question":"Il trekking in cammello è adatto ai bambini?","answer":"I bambini dai sei anni in su possono salire con un genitore, con un cammelliere che cammina accanto a ogni cammello per tutto il percorso. Sotto i sei anni, consigliamo invece la visita al campo al tramonto."}', 10);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('3273c376-bb74-4178-9e9d-1f10580a48ae', 'faq', '{"question":"Cosa succede in caso di gravidanza o esigenze particolari di mobilità?","answer":"Comunicatecelo al momento della prenotazione — preferiamo indirizzarvi verso l''escursione giusta piuttosto che rifiutarvi l''accesso all''ingresso."}', 11);

-- Home — IT
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('7e6c3e97-a9b5-4e33-8015-c458fcfddf93', 'Home', 'home', 'IT', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('7e6c3e97-a9b5-4e33-8015-c458fcfddf93', 'steps', '{"eyebrow":"Come funziona","items":[{"title":"Scegli la tua avventura","body":"Scegli una singola attività oppure combina cammello, quad e tavola in un''unica spedizione al tramonto."},{"title":"Prenota il tuo orario","body":"Prenota una fascia mattutina o dell''ora dorata. Attrezzatura, guide e trasferimenti sono tutti inclusi."},{"title":"Ritrovo al cancello","body":"Arriva al cancello di Sabria, incontra la tua guida e parti attraverso il Sahara a cielo aperto."}]}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('7e6c3e97-a9b5-4e33-8015-c458fcfddf93', 'bookDirect', '{"eyebrow":"Prenota direttamente","lead":"Organizziamo noi stessi ogni uscita in questa pagina. Prenotare qui significa che nessuna piattaforma trattiene una commissione — il risparmio va a voi, e le vostre domande arrivano direttamente alle persone che vi aspetteranno al cancello.","ctaLabel":"Prenota direttamente ora","headingHere":"Direttamente con Dunes Insolites","advantages":[{"text":"Miglior prezzo — nessuna commissione di piattaforma aggiuntiva"},{"text":"Parlate con la guida che conduce la vostra uscita, non con un call center"},{"text":"Cancellazione gratuita fino a 24 ore prima"},{"text":"Pagamento al cancello — nessun addebito per prenotare"},{"text":"Ritiro flessibile dal vostro hotel a Douz o Kebili"},{"text":"Le vostre foto e video inviati la mattina successiva"}]}', 1);

-- FAQ — DA
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'Alt hvad der er værd at vide, før du booker', 'faq', 'DA', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'richText', '{"heading":"Booking og afbestilling","content":""}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'faq', '{"question":"Hvad er afbestillingspolitikken?","answer":"Mere end 24 timer før afgang: ingen gebyr. Inden for 24 timer: 50 % af turprisen. Udeblivelse ved porten: fuld pris. Hvis det er os, der aflyser — vejr, udstyr eller en anden grund på vores side — vælger du mellem fuld refundering eller gratis omlægning."}', 1);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'faq', '{"question":"Skal jeg betale, når jeg booker?","answer":"Nej. Der bliver ikke trukket noget ved booking — betalingen sker ved porten eller via et sikkert link."}', 2);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'faq', '{"question":"Hvad sker der, hvis vejret slår om på dagen for min tur?","answer":"Sandstorme og kraftig vind betyder aflysning, med fuld refundering eller gratis omlægning. Den beslutning træffes af cheflederen, aldrig af bookingkontoret."}', 3);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'richText', '{"heading":"Praktisk information","content":""}', 4);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'faq', '{"question":"Hvad skal jeg have på og med?","answer":"Lukkede sko, lange ærmer og solbriller om dagen; et varmt lag til aftenen, da ørkennætter er kolde selv efter en varm dag. Vi uddeler et chèche (hoved- og halstørklæde) ved porten."}', 5);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'faq', '{"question":"Er der mobildækning i Sabria?","answer":"Kun med mellemrum. Hver guide bærer en opladet satellitmessenger og radio, og basen ved porten kender hver rute og forventet returtid."}', 6);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'faq', '{"question":"Kan I imødekomme kost- eller medicinske behov?","answer":"Ja — fortæl os det, når du booker. Vi tilbyder vegetariske, veganske og glutenfrie muligheder i lejren, og vores guider bliver briefet om enhver tilstand, du fortæller os om."}', 7);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'richText', '{"heading":"Alder og deltagelse","content":""}', 8);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'faq', '{"question":"Kræver det erfaring at køre quad?","answer":"Nej. Quaderne er automatiske, og hver session starter med en briefing og en prøverunde på fladt terræn, før man tager ud i klitterne. Førere skal være mindst 16 år med billede-id."}', 9);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'faq', '{"question":"Er kameltrekket egnet til børn?","answer":"Børn fra seks år kan ride med en forælder, mens en kameldriver går ved siden af hver kamel hele vejen. Under seks år anbefaler vi i stedet besøget i lejren ved solnedgang."}', 10);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('e9c2dbc2-ae6e-49f2-b376-23a410420ac7', 'faq', '{"question":"Hvad med graviditet eller særlige mobilitetsbehov?","answer":"Fortæl os det, når du booker — vi vil hellere henvise dig til den rigtige tur end afvise dig ved porten."}', 11);

-- Home — DA
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('b4e92c52-5843-4b9d-a39a-7c170c4ed51a', 'Forside', 'home', 'DA', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('b4e92c52-5843-4b9d-a39a-7c170c4ed51a', 'steps', '{"eyebrow":"Sådan fungerer det","items":[{"title":"Vælg dit eventyr","body":"Vælg en enkelt aktivitet, eller kombiner kamel, quad og board til én solnedgangsekspedition."},{"title":"Book dit tidsrum","body":"Reserver en morgen- eller golden-hour-plads. Udstyr, guider og transport er alt sammen inkluderet."},{"title":"Mødes ved porten","body":"Ankom til Sabria-porten, mød din guide, og tag afsted ud i den åbne Sahara."}]}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('b4e92c52-5843-4b9d-a39a-7c170c4ed51a', 'bookDirect', '{"eyebrow":"Book direkte","lead":"Vi driver selv hver eneste tur på denne side. At booke her betyder, at ingen platform tager et gebyr — så besparelsen går til dig, og dine spørgsmål går direkte til dem, der står ved porten.","ctaLabel":"Book direkte nu","headingHere":"Direkte hos Dunes Insolites","advantages":[{"text":"Bedste pris — ingen ekstra platformsprovision"},{"text":"Tal med guiden, der leder din tur, ikke et callcenter"},{"text":"Gratis afbestilling op til 24 timer før"},{"text":"Betal ved porten — intet trækkes ved booking"},{"text":"Fleksibel afhentning fra dit hotel i Douz eller Kebili"},{"text":"Dine billeder og videoer sendt næste morgen"}]}', 1);

-- FAQ — AR
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'كل ما يستحق معرفته قبل الحجز', 'faq', 'AR', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'richText', '{"heading":"الحجز والإلغاء","content":""}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'faq', '{"question":"ما هي سياسة الإلغاء؟","answer":"الإلغاء قبل أكثر من 24 ساعة من الانطلاق: بدون أي رسوم. الإلغاء خلال 24 ساعة: 50٪ من سعر الرحلة. عدم الحضور عند البوابة: السعر كاملاً. إذا كان الإلغاء من جانبنا — بسبب الطقس أو المعدات أو أي سبب آخر يخصنا — يمكنكم الاختيار بين استرداد كامل المبلغ أو إعادة جدولة مجانية."}', 1);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'faq', '{"question":"هل أدفع عند الحجز؟","answer":"لا. لا يتم خصم أي مبلغ عند الحجز — يتم الدفع عند البوابة أو عبر رابط آمن."}', 2);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'faq', '{"question":"ماذا يحدث إذا ساء الطقس يوم رحلتي؟","answer":"العواصف الرملية والرياح القوية تعني الإلغاء، مع استرداد كامل للمبلغ أو إعادة جدولة مجانية. هذا القرار يتخذه كبير المرشدين، وليس مكتب الحجوزات أبداً."}', 3);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'richText', '{"heading":"معلومات عملية","content":""}', 4);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'faq', '{"question":"ماذا يجب أن أرتدي وأحضر؟","answer":"أحذية مغلقة، وأكمام طويلة، ونظارات شمسية للنهار؛ وطبقة دافئة للمساء، فليالي الصحراء باردة حتى بعد نهار حار. نوزّع الشاش (وشاح للرأس والرقبة) عند البوابة."}', 5);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'faq', '{"question":"هل توجد تغطية للهاتف في سبرية؟","answer":"متقطعة في أحسن الأحوال. كل مرشد يحمل جهاز اتصال عبر الأقمار الصناعية مشحوناً وجهاز لاسلكي، والقاعدة عند البوابة تعرف مسار كل مجموعة ووقت عودتها المتوقع."}', 6);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'faq', '{"question":"هل يمكنكم تلبية احتياجات غذائية أو طبية؟","answer":"نعم — أخبرونا بذلك عند الحجز. نوفر خيارات نباتية ونباتية صرفة وخالية من الغلوتين في المخيم، ومرشدونا على علم بأي حالة تُخبروننا بها."}', 7);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'richText', '{"heading":"السن والمشاركة","content":""}', 8);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'faq', '{"question":"هل تحتاج قيادة الدراجة الرباعية إلى خبرة؟","answer":"لا. الدراجات الرباعية أوتوماتيكية، وكل جلسة تبدأ بشرح تمهيدي وجولة تجريبية على أرض مستوية قبل التوجه إلى الكثبان. يجب أن يكون السائق 16 عاماً فأكثر ويحمل بطاقة هوية بصورة."}', 9);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'faq', '{"question":"هل تناسب رحلة الجمل الأطفال؟","answer":"يمكن للأطفال من سن السادسة فأكثر الركوب برفقة أحد الوالدين، مع سير قائد الجمل بجانب كل جمل طوال الطريق. لمن هم دون السادسة، ننصح بزيارة المخيم عند الغروب بدلاً من ذلك."}', 10);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('2b0a3237-090e-4909-a582-85e2717e7978', 'faq', '{"question":"ماذا عن الحمل أو احتياجات الحركة الخاصة؟","answer":"أخبرونا بذلك عند الحجز — نفضّل أن نوجهكم إلى الرحلة المناسبة بدلاً من رفض دخولكم عند البوابة."}', 11);

-- Home — AR
INSERT INTO pages (page_id, title, slug, locale, company_type, status, published_at, no_index, no_follow, created_at, updated_at)
VALUES ('b87e5faf-4296-4474-bbc5-eb896e62bdab', 'الرئيسية', 'home', 'AR', 'DUNES_INSOLITES', 'PUBLISHED', now(), false, false, now(), now());

INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('b87e5faf-4296-4474-bbc5-eb896e62bdab', 'steps', '{"eyebrow":"كيف يعمل الأمر","items":[{"title":"اختر مغامرتك","body":"اختر نشاطًا واحدًا أو ادمج الجمل والدراجة الرباعية واللوح في رحلة واحدة عند الغروب."},{"title":"احجز موعدك","body":"احجز فترة صباحية أو فترة الغروب الذهبي. المعدات والمرشدون والنقل جميعها مشمولة."},{"title":"التقوا عند البوابة","body":"اصلوا إلى بوابة سابرية، وتعرفوا على مرشدكم، وانطلقوا عبر الصحراء الكبرى المفتوحة."}]}', 0);
INSERT INTO page_blocks (page_id, type, data_json, display_order) VALUES ('b87e5faf-4296-4474-bbc5-eb896e62bdab', 'bookDirect', '{"eyebrow":"احجز مباشرة","lead":"نحن ندير كل رحلة في هذه الصفحة بأنفسنا. الحجز هنا يعني ألا تأخذ أي منصة عمولة — فالتوفير يعود إليكم، وتصل أسئلتكم مباشرة إلى من سيكونون في انتظاركم عند البوابة.","ctaLabel":"احجز مباشرة الآن","headingHere":"مباشرة مع دون إنسوليت","advantages":[{"text":"أفضل سعر — دون عمولة منصة إضافية"},{"text":"تحدثوا مع المرشد الذي يقود رحلتكم، لا مع مركز اتصال"},{"text":"إلغاء مجاني حتى 24 ساعة قبل الموعد"},{"text":"الدفع عند البوابة — لا يُخصم شيء عند الحجز"},{"text":"نقل مرن من فندقكم في دوز أو قبلي"},{"text":"صوركم ومقاطع الفيديو تُرسل في صباح اليوم التالي"}]}', 1);

