-- V1__baseline_schema.sql
-- Flyway baseline for the Dune Insolite database.
--
-- SOURCE: pg_dump --schema-only of the database on 2 Sep 2026, which until now
-- was managed entirely by Hibernate `ddl-auto: update`. This file IS that
-- schema, verbatim except for stripped psql meta-commands.
--
-- On an EXISTING database this script is NEVER executed: baseline-on-migrate
-- + baseline-version=1 make Flyway stamp a marker row and skip to V2+. It runs
-- ONLY when creating a brand-new empty database.
--
-- BEFORE PRODUCTION CUTOVER: if a real production database already exists,
-- diff this against pg_dump of that database and reconcile drift. See
-- docs/runbooks/database-migrations.md.

--
--

--
-- Name: account_action_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_action_tokens (
    token_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(64) NOT NULL,
    type character varying(255) NOT NULL,
    used_at timestamp(6) without time zone,
    user_id uuid NOT NULL,
    CONSTRAINT account_action_tokens_type_check CHECK (((type)::text = ANY ((ARRAY['EMAIL_VERIFY'::character varying, 'PASSWORD_RESET'::character varying])::text[])))
);

--
-- Name: availability_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.availability_blocks (
    availability_block_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date date NOT NULL,
    note character varying(255),
    tour_type_id uuid NOT NULL
);

--
-- Name: camping_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.camping_settings (
    id bigint NOT NULL,
    max_capacity integer NOT NULL,
    updated_at timestamp(6) without time zone
);

--
-- Name: chauffeurs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chauffeurs (
    chauffeur_id uuid NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    phone_number character varying(255),
    reservation_id uuid NOT NULL
);

--
-- Name: content_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_blocks (
    block_id uuid NOT NULL,
    company_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    data_json text,
    label character varying(255) NOT NULL,
    locale character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT content_blocks_company_type_check CHECK (((company_type)::text = ANY ((ARRAY['DUNES_INSOLITES'::character varying, 'ROUTE_INSOLITE'::character varying])::text[]))),
    CONSTRAINT content_blocks_locale_check CHECK (((locale)::text = ANY ((ARRAY['FR'::character varying, 'EN'::character varying, 'DE'::character varying, 'IT'::character varying, 'DA'::character varying, 'AR'::character varying])::text[])))
);

--
-- Name: document_sequences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_sequences (
    id bigint NOT NULL,
    last_number integer NOT NULL,
    type character varying(20) NOT NULL,
    year integer NOT NULL
);

--
-- Name: document_sequences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document_sequences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_sequences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: extra_highlights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extra_highlights (
    extra_id uuid NOT NULL,
    highlight text,
    display_order integer NOT NULL
);

--
-- Name: extra_included_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extra_included_items (
    extra_id uuid NOT NULL,
    item text,
    display_order integer NOT NULL
);

--
-- Name: extra_languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extra_languages (
    extra_id uuid NOT NULL,
    language character varying(255),
    CONSTRAINT extra_languages_language_check CHECK (((language)::text = ANY ((ARRAY['FR'::character varying, 'EN'::character varying, 'AR'::character varying])::text[])))
);

--
-- Name: extra_not_included_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extra_not_included_items (
    extra_id uuid NOT NULL,
    item text,
    display_order integer NOT NULL
);

--
-- Name: extra_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extra_photos (
    extra_id uuid NOT NULL,
    caption character varying(255),
    url character varying(255) NOT NULL,
    display_order integer NOT NULL
);

--
-- Name: extra_program_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extra_program_steps (
    extra_id uuid NOT NULL,
    description text,
    label character varying(255),
    title character varying(255),
    step_order integer NOT NULL
);

--
-- Name: extra_translation_highlights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extra_translation_highlights (
    extra_translation_id uuid NOT NULL,
    highlight text,
    display_order integer NOT NULL
);

--
-- Name: extra_translation_included_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extra_translation_included_items (
    extra_translation_id uuid NOT NULL,
    item text,
    display_order integer NOT NULL
);

--
-- Name: extra_translation_not_included_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extra_translation_not_included_items (
    extra_translation_id uuid NOT NULL,
    item text,
    display_order integer NOT NULL
);

--
-- Name: extra_translation_program_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extra_translation_program_steps (
    extra_translation_id uuid NOT NULL,
    description text,
    label character varying(255),
    title character varying(255),
    step_order integer NOT NULL
);

--
-- Name: extra_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extra_translations (
    extra_translation_id uuid NOT NULL,
    about_text text,
    description text,
    locale character varying(255) NOT NULL,
    name character varying(255),
    extra_id uuid NOT NULL,
    CONSTRAINT extra_translations_locale_check CHECK (((locale)::text = ANY ((ARRAY['EN'::character varying, 'DE'::character varying, 'IT'::character varying, 'DA'::character varying, 'AR'::character varying])::text[])))
);

--
-- Name: extras; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.extras (
    extra_id uuid NOT NULL,
    about_text text,
    average_rating double precision,
    free_cancellation boolean,
    cancellation_hours_before_deadline integer,
    cover_photo_url character varying(255),
    description text,
    duration character varying(255),
    duration_end_time time(0) without time zone,
    duration_start_time time(0) without time zone,
    group_size_type character varying(255),
    is_active boolean NOT NULL,
    location character varying(255),
    meeting_point character varying(255),
    name character varying(255) NOT NULL,
    review_count integer,
    slug character varying(255),
    tva double precision NOT NULL,
    unit_price double precision NOT NULL,
    CONSTRAINT extras_group_size_type_check CHECK (((group_size_type)::text = ANY ((ARRAY['PETIT_GROUPE'::character varying, 'GROUPE_MOYEN'::character varying, 'TOUTES_TAILLES'::character varying, 'PRIVATIF'::character varying])::text[])))
);

--
-- Name: guides; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guides (
    guide_id uuid NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    phone_number character varying(255),
    reservation_id uuid NOT NULL
);

--
-- Name: invoice_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoice_items (
    invoice_item_id uuid NOT NULL,
    activity_date date,
    activity_end_date date,
    description character varying(255) NOT NULL,
    item_type character varying(255) NOT NULL,
    line_number integer NOT NULL,
    quantity integer NOT NULL,
    tva double precision NOT NULL,
    unit_price double precision NOT NULL,
    invoice_id uuid NOT NULL
);

--
-- Name: invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoices (
    invoice_id uuid NOT NULL,
    company_type character varying(255),
    currency character varying(3) NOT NULL,
    due_date date,
    invoice_date date NOT NULL,
    invoice_number character varying(255) NOT NULL,
    invoice_type character varying(255) NOT NULL,
    paid_amount double precision NOT NULL,
    payment_status character varying(255) NOT NULL,
    snapshot_data text,
    status character varying(255) NOT NULL,
    timbre_fiscal double precision,
    total_amount double precision NOT NULL,
    total_ht double precision,
    total_ttc double precision,
    tva_amount double precision,
    tva_rate double precision,
    reservation_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT invoices_company_type_check CHECK (((company_type)::text = ANY ((ARRAY['DUNES_INSOLITES'::character varying, 'ROUTE_INSOLITE'::character varying])::text[]))),
    CONSTRAINT invoices_currency_check CHECK (((currency)::text = ANY ((ARRAY['TND'::character varying, 'EUR'::character varying, 'USD'::character varying])::text[]))),
    CONSTRAINT invoices_invoice_type_check CHECK (((invoice_type)::text = ANY ((ARRAY['STANDARD'::character varying, 'PROFORMA'::character varying, 'CREDIT_NOTE'::character varying])::text[]))),
    CONSTRAINT invoices_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['UNPAID'::character varying, 'PARTIALLY_PAID'::character varying, 'PAID'::character varying, 'OVERDUE'::character varying, 'REFUNDED'::character varying])::text[]))),
    CONSTRAINT invoices_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SENT'::character varying, 'CANCELLED'::character varying])::text[])))
);

--
-- Name: maintenance_windows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.maintenance_windows (
    maintenance_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    ends_at timestamp(6) without time zone,
    is_active boolean NOT NULL,
    message text,
    path character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

--
-- Name: media_assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.media_assets (
    asset_id uuid NOT NULL,
    company_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    filename character varying(255) NOT NULL,
    mime_type character varying(255) NOT NULL,
    size_bytes bigint NOT NULL,
    stored_filename character varying(255) NOT NULL,
    CONSTRAINT media_assets_company_type_check CHECK (((company_type)::text = ANY ((ARRAY['DUNES_INSOLITES'::character varying, 'ROUTE_INSOLITE'::character varying])::text[])))
);

--
-- Name: navigation_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.navigation_items (
    nav_item_id uuid NOT NULL,
    company_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    label character varying(255) NOT NULL,
    locale character varying(255) NOT NULL,
    menu_type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    url character varying(255) NOT NULL,
    CONSTRAINT navigation_items_company_type_check CHECK (((company_type)::text = ANY ((ARRAY['DUNES_INSOLITES'::character varying, 'ROUTE_INSOLITE'::character varying])::text[]))),
    CONSTRAINT navigation_items_locale_check CHECK (((locale)::text = ANY ((ARRAY['FR'::character varying, 'EN'::character varying, 'DE'::character varying, 'IT'::character varying, 'DA'::character varying, 'AR'::character varying])::text[]))),
    CONSTRAINT navigation_items_menu_type_check CHECK (((menu_type)::text = ANY ((ARRAY['NONE'::character varying, 'EXPERIENCES'::character varying, 'STAYS'::character varying])::text[])))
);

--
-- Name: newsletter_subscribers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.newsletter_subscribers (
    id uuid NOT NULL,
    email character varying(255) NOT NULL,
    subscribed_at timestamp(6) without time zone NOT NULL
);

--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    notification_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    message text NOT NULL,
    reservation_id uuid,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['RESERVATION_CREATED'::character varying, 'RESERVATION_CONFIRMED'::character varying, 'RESERVATION_CANCELLED'::character varying, 'RESERVATION_REJECTED'::character varying, 'RESERVATION_UPDATED'::character varying, 'PAYMENT_RECEIVED'::character varying, 'PAYMENT_COMPLETED'::character varying, 'INVOICE_SENT'::character varying, 'PROMO_CODE'::character varying, 'STAFF_ASSIGNED'::character varying, 'STAFF_UPDATED'::character varying, 'GENERAL'::character varying])::text[])))
);

--
-- Name: page_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.page_blocks (
    page_id uuid NOT NULL,
    data_json text,
    type character varying(255) NOT NULL,
    display_order integer NOT NULL
);

--
-- Name: pages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pages (
    page_id uuid NOT NULL,
    canonical_url character varying(255),
    company_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    focus_keyword character varying(255),
    locale character varying(255) NOT NULL,
    meta_description text,
    no_follow boolean NOT NULL,
    no_index boolean NOT NULL,
    og_description text,
    og_image_url character varying(255),
    og_title character varying(255),
    published_at timestamp(6) without time zone,
    seo_title character varying(255),
    slug character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    category character varying(255),
    CONSTRAINT pages_category_check CHECK (((category)::text = 'GUIDE'::text)),
    CONSTRAINT pages_company_type_check CHECK (((company_type)::text = ANY ((ARRAY['DUNES_INSOLITES'::character varying, 'ROUTE_INSOLITE'::character varying])::text[]))),
    CONSTRAINT pages_locale_check CHECK (((locale)::text = ANY ((ARRAY['FR'::character varying, 'EN'::character varying, 'DE'::character varying, 'IT'::character varying, 'DA'::character varying, 'AR'::character varying])::text[]))),
    CONSTRAINT pages_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])))
);

--
-- Name: participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.participants (
    participant_id uuid NOT NULL,
    age integer NOT NULL,
    full_name character varying(255) NOT NULL,
    is_adult boolean NOT NULL,
    reservation_id uuid NOT NULL
);

--
-- Name: redirects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.redirects (
    redirect_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    from_path character varying(255) NOT NULL,
    status_code integer NOT NULL,
    to_path character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

--
-- Name: reservation_extras; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation_extras (
    reservation_extra_id uuid NOT NULL,
    activity_date date,
    catalog_extra_id uuid,
    description text,
    duration character varying(255),
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    total_price double precision,
    tva double precision NOT NULL,
    unit_price double precision NOT NULL,
    reservation_id uuid NOT NULL
);

--
-- Name: reservation_repartitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation_repartitions (
    repartition_id uuid NOT NULL,
    number_of_tentes integer NOT NULL,
    tente_type character varying(255) NOT NULL,
    reservation_id uuid NOT NULL,
    reservation_tour_hebergement_id uuid,
    reservation_tour_type_id uuid,
    CONSTRAINT reservation_repartitions_tente_type_check CHECK (((tente_type)::text = ANY ((ARRAY['SINGLE'::character varying, 'DOUBLE'::character varying, 'TRIPLE'::character varying, 'X4'::character varying, 'X5'::character varying, 'X6'::character varying, 'X7'::character varying])::text[])))
);

--
-- Name: reservation_tour_hebergements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation_tour_hebergements (
    hebergement_id uuid NOT NULL,
    activity_date date NOT NULL,
    catalog_tour_type_id uuid,
    description text,
    duration character varying(255),
    name character varying(255) NOT NULL,
    number_of_adults integer NOT NULL,
    number_of_children integer NOT NULL,
    number_of_nights integer,
    reservation_tour_id uuid NOT NULL
);

--
-- Name: reservation_tour_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation_tour_types (
    reservation_tour_type_id uuid NOT NULL,
    activity_date date,
    adult_price double precision NOT NULL,
    catalog_tour_type_id uuid,
    child_price double precision NOT NULL,
    description text,
    duration character varying(255),
    name character varying(255) NOT NULL,
    number_of_adults integer NOT NULL,
    number_of_children integer NOT NULL,
    number_of_nights integer,
    tva double precision NOT NULL,
    reservation_id uuid NOT NULL
);

--
-- Name: reservation_tours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation_tours (
    reservation_tour_id uuid NOT NULL,
    adult_price double precision NOT NULL,
    catalog_tour_id uuid,
    child_price double precision NOT NULL,
    departure_date date NOT NULL,
    description text,
    duration character varying(255),
    name character varying(255) NOT NULL,
    number_of_adults integer NOT NULL,
    number_of_children integer NOT NULL,
    total_price double precision NOT NULL,
    tva double precision NOT NULL,
    reservation_id uuid NOT NULL
);

--
-- Name: reservations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservations (
    reservation_id uuid NOT NULL,
    check_in_date date,
    check_out_date date,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(3),
    deleted_at timestamp(6) without time zone,
    demande_special text,
    exchange_rate_applied double precision,
    group_leader_name character varying(255),
    group_name character varying(255),
    number_of_adults integer NOT NULL,
    number_of_children integer NOT NULL,
    payment_link character varying(255),
    promo_code character varying(255),
    rejection_reason text,
    reservation_type character varying(255) NOT NULL,
    service_date date,
    status character varying(255) NOT NULL,
    total_amount double precision,
    total_extras_amount double precision,
    updated_at timestamp(6) without time zone,
    source_ref_id uuid,
    user_id uuid NOT NULL,
    CONSTRAINT reservations_currency_check CHECK (((currency)::text = ANY ((ARRAY['TND'::character varying, 'EUR'::character varying, 'USD'::character varying])::text[]))),
    CONSTRAINT reservations_reservation_type_check CHECK (((reservation_type)::text = ANY ((ARRAY['HEBERGEMENT'::character varying, 'TOURS'::character varying, 'EXTRAS'::character varying])::text[]))),
    CONSTRAINT reservations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CHECKED_IN'::character varying, 'CANCELLED'::character varying, 'REJECTED'::character varying, 'COMPLETED'::character varying])::text[])))
);

--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    review_id uuid NOT NULL,
    comment text,
    created_at timestamp(6) without time zone NOT NULL,
    product_id uuid NOT NULL,
    product_type character varying(255) NOT NULL,
    rating integer NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT reviews_product_type_check CHECK (((product_type)::text = ANY ((ARRAY['TOURTYPE'::character varying, 'TOUR'::character varying, 'EXTRA'::character varying])::text[])))
);

--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    id uuid NOT NULL,
    level character varying(255) NOT NULL,
    resource character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT role_permissions_level_check CHECK (((level)::text = ANY ((ARRAY['NONE'::character varying, 'READ'::character varying, 'EDIT'::character varying, 'FULL'::character varying])::text[]))),
    CONSTRAINT role_permissions_resource_check CHECK (((resource)::text = ANY ((ARRAY['USERS'::character varying, 'RESERVATIONS'::character varying, 'INVOICES'::character varying, 'TRANSACTIONS'::character varying, 'TOURS'::character varying, 'TOUR_TYPES'::character varying, 'EXTRAS'::character varying, 'REVIEWS'::character varying, 'AVAILABILITY'::character varying, 'PAGES'::character varying, 'CONTENT_BLOCKS'::character varying, 'MEDIA'::character varying, 'NAVIGATION'::character varying, 'REDIRECTS'::character varying, 'MAINTENANCE_WINDOWS'::character varying])::text[]))),
    CONSTRAINT role_permissions_role_check CHECK (((role)::text = ANY ((ARRAY['CLIENT'::character varying, 'PARTENAIRE'::character varying, 'CAMPING'::character varying, 'ADMIN'::character varying])::text[])))
);

--
-- Name: sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sources (
    source_id uuid NOT NULL,
    name character varying(255) NOT NULL
);

--
-- Name: tour_highlights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_highlights (
    tour_id uuid NOT NULL,
    highlight text,
    display_order integer NOT NULL
);

--
-- Name: tour_included_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_included_items (
    tour_id uuid NOT NULL,
    item text,
    display_order integer NOT NULL
);

--
-- Name: tour_languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_languages (
    tour_id uuid NOT NULL,
    language character varying(255),
    CONSTRAINT tour_languages_language_check CHECK (((language)::text = ANY ((ARRAY['FR'::character varying, 'EN'::character varying, 'AR'::character varying])::text[])))
);

--
-- Name: tour_not_included_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_not_included_items (
    tour_id uuid NOT NULL,
    item text,
    display_order integer NOT NULL
);

--
-- Name: tour_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_photos (
    tour_id uuid NOT NULL,
    caption character varying(255),
    url character varying(255) NOT NULL,
    display_order integer NOT NULL
);

--
-- Name: tour_program_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_program_steps (
    tour_id uuid NOT NULL,
    description text,
    label character varying(255),
    title character varying(255),
    step_order integer NOT NULL
);

--
-- Name: tour_type_highlights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_type_highlights (
    tour_type_id uuid NOT NULL,
    highlight text,
    display_order integer NOT NULL
);

--
-- Name: tour_type_included_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_type_included_items (
    tour_type_id uuid NOT NULL,
    item text,
    display_order integer NOT NULL
);

--
-- Name: tour_type_languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_type_languages (
    tour_type_id uuid NOT NULL,
    language character varying(255),
    CONSTRAINT tour_type_languages_language_check CHECK (((language)::text = ANY ((ARRAY['FR'::character varying, 'EN'::character varying, 'AR'::character varying])::text[])))
);

--
-- Name: tour_type_not_included_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_type_not_included_items (
    tour_type_id uuid NOT NULL,
    item text,
    display_order integer NOT NULL
);

--
-- Name: tour_type_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_type_photos (
    tour_type_id uuid NOT NULL,
    caption character varying(255),
    url character varying(255) NOT NULL,
    display_order integer NOT NULL
);

--
-- Name: tour_type_program_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_type_program_steps (
    tour_type_id uuid NOT NULL,
    description text,
    label character varying(255),
    title character varying(255),
    step_order integer NOT NULL
);

--
-- Name: tour_type_translation_highlights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_type_translation_highlights (
    tour_type_translation_id uuid NOT NULL,
    highlight text,
    display_order integer NOT NULL
);

--
-- Name: tour_type_translation_included_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_type_translation_included_items (
    tour_type_translation_id uuid NOT NULL,
    item text,
    display_order integer NOT NULL
);

--
-- Name: tour_type_translation_not_included_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_type_translation_not_included_items (
    tour_type_translation_id uuid NOT NULL,
    item text,
    display_order integer NOT NULL
);

--
-- Name: tour_type_translation_program_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_type_translation_program_steps (
    tour_type_translation_id uuid NOT NULL,
    description text,
    label character varying(255),
    title character varying(255),
    step_order integer NOT NULL
);

--
-- Name: tour_type_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_type_translations (
    tour_type_translation_id uuid NOT NULL,
    about_text text,
    description text,
    locale character varying(255) NOT NULL,
    name character varying(255),
    tour_type_id uuid NOT NULL,
    CONSTRAINT tour_type_translations_locale_check CHECK (((locale)::text = ANY ((ARRAY['EN'::character varying, 'DE'::character varying, 'IT'::character varying, 'DA'::character varying, 'AR'::character varying])::text[])))
);

--
-- Name: tour_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_types (
    tour_type_id uuid NOT NULL,
    about_text text,
    average_rating double precision,
    free_cancellation boolean,
    cancellation_hours_before_deadline integer,
    cover_photo_url character varying(255),
    description text,
    duration character varying(255),
    group_size_type character varying(255),
    is_active boolean NOT NULL,
    location character varying(255),
    meeting_point character varying(255),
    name character varying(255) NOT NULL,
    partner_adult_price double precision NOT NULL,
    partner_child_price double precision NOT NULL,
    passenger_adult_price double precision NOT NULL,
    passenger_child_price double precision NOT NULL,
    review_count integer,
    slug character varying(255),
    tva double precision NOT NULL,
    CONSTRAINT tour_types_group_size_type_check CHECK (((group_size_type)::text = ANY ((ARRAY['PETIT_GROUPE'::character varying, 'GROUPE_MOYEN'::character varying, 'TOUTES_TAILLES'::character varying, 'PRIVATIF'::character varying])::text[])))
);

--
-- Name: tours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tours (
    tour_id uuid NOT NULL,
    about_text text,
    average_rating double precision,
    free_cancellation boolean,
    cancellation_hours_before_deadline integer,
    cover_photo_url character varying(255),
    description text,
    duration character varying(255),
    group_size_type character varying(255),
    is_active boolean NOT NULL,
    location character varying(255),
    meeting_point character varying(255),
    name character varying(255) NOT NULL,
    partner_adult_price double precision NOT NULL,
    partner_child_price double precision NOT NULL,
    passenger_adult_price double precision NOT NULL,
    passenger_child_price double precision NOT NULL,
    review_count integer,
    slug character varying(255),
    tva double precision NOT NULL,
    CONSTRAINT tours_group_size_type_check CHECK (((group_size_type)::text = ANY ((ARRAY['PETIT_GROUPE'::character varying, 'GROUPE_MOYEN'::character varying, 'TOUTES_TAILLES'::character varying, 'PRIVATIF'::character varying])::text[])))
);

--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    transaction_id uuid NOT NULL,
    amount double precision NOT NULL,
    currency character varying(3) NOT NULL,
    payment_method character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    transaction_number character varying(255) NOT NULL,
    invoice_id uuid,
    reservation_id uuid NOT NULL,
    CONSTRAINT transactions_currency_check CHECK (((currency)::text = ANY ((ARRAY['TND'::character varying, 'EUR'::character varying, 'USD'::character varying])::text[]))),
    CONSTRAINT transactions_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'CREDIT_CARD'::character varying, 'DEBIT_CARD'::character varying, 'BANK_TRANSFER'::character varying, 'ONLINE'::character varying, 'CHEQUE'::character varying])::text[]))),
    CONSTRAINT transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying, 'CANCELLED'::character varying])::text[])))
);

--
-- Name: user_product_remises; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_product_remises (
    id uuid NOT NULL,
    adult_remise double precision,
    child_remise double precision,
    product_id uuid NOT NULL,
    product_name character varying(255) NOT NULL,
    product_type character varying(255) NOT NULL,
    unit_remise double precision,
    user_id uuid NOT NULL,
    CONSTRAINT user_product_remises_product_type_check CHECK (((product_type)::text = ANY ((ARRAY['TOURTYPE'::character varying, 'TOUR'::character varying, 'EXTRA'::character varying])::text[])))
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id uuid NOT NULL,
    agency_address character varying(255),
    email character varying(255) NOT NULL,
    has_special_remise boolean DEFAULT false NOT NULL,
    loyalty_points integer,
    loyalty_tier character varying(255),
    matricule_fiscal character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255),
    role character varying(255) NOT NULL,
    terms_accepted_at timestamp(6) without time zone,
    CONSTRAINT users_loyalty_tier_check CHECK (((loyalty_tier)::text = ANY ((ARRAY['BRONZE'::character varying, 'SILVER'::character varying, 'GOLD'::character varying, 'PLATINUM'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CLIENT'::character varying, 'PARTENAIRE'::character varying, 'CAMPING'::character varying, 'ADMIN'::character varying])::text[])))
);

--
-- Name: account_action_tokens account_action_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_action_tokens
    ADD CONSTRAINT account_action_tokens_pkey PRIMARY KEY (token_id);

--
-- Name: availability_blocks availability_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.availability_blocks
    ADD CONSTRAINT availability_blocks_pkey PRIMARY KEY (availability_block_id);

--
-- Name: camping_settings camping_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.camping_settings
    ADD CONSTRAINT camping_settings_pkey PRIMARY KEY (id);

--
-- Name: chauffeurs chauffeurs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chauffeurs
    ADD CONSTRAINT chauffeurs_pkey PRIMARY KEY (chauffeur_id);

--
-- Name: content_blocks content_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_blocks
    ADD CONSTRAINT content_blocks_pkey PRIMARY KEY (block_id);

--
-- Name: document_sequences document_sequences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_sequences
    ADD CONSTRAINT document_sequences_pkey PRIMARY KEY (id);

--
-- Name: extra_highlights extra_highlights_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_highlights
    ADD CONSTRAINT extra_highlights_pkey PRIMARY KEY (extra_id, display_order);

--
-- Name: extra_included_items extra_included_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_included_items
    ADD CONSTRAINT extra_included_items_pkey PRIMARY KEY (extra_id, display_order);

--
-- Name: extra_not_included_items extra_not_included_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_not_included_items
    ADD CONSTRAINT extra_not_included_items_pkey PRIMARY KEY (extra_id, display_order);

--
-- Name: extra_photos extra_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_photos
    ADD CONSTRAINT extra_photos_pkey PRIMARY KEY (extra_id, display_order);

--
-- Name: extra_program_steps extra_program_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_program_steps
    ADD CONSTRAINT extra_program_steps_pkey PRIMARY KEY (extra_id, step_order);

--
-- Name: extra_translation_highlights extra_translation_highlights_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_translation_highlights
    ADD CONSTRAINT extra_translation_highlights_pkey PRIMARY KEY (extra_translation_id, display_order);

--
-- Name: extra_translation_included_items extra_translation_included_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_translation_included_items
    ADD CONSTRAINT extra_translation_included_items_pkey PRIMARY KEY (extra_translation_id, display_order);

--
-- Name: extra_translation_not_included_items extra_translation_not_included_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_translation_not_included_items
    ADD CONSTRAINT extra_translation_not_included_items_pkey PRIMARY KEY (extra_translation_id, display_order);

--
-- Name: extra_translation_program_steps extra_translation_program_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_translation_program_steps
    ADD CONSTRAINT extra_translation_program_steps_pkey PRIMARY KEY (extra_translation_id, step_order);

--
-- Name: extra_translations extra_translations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_translations
    ADD CONSTRAINT extra_translations_pkey PRIMARY KEY (extra_translation_id);

--
-- Name: extras extras_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extras
    ADD CONSTRAINT extras_pkey PRIMARY KEY (extra_id);

--
-- Name: guides guides_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guides
    ADD CONSTRAINT guides_pkey PRIMARY KEY (guide_id);

--
-- Name: invoice_items invoice_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_items
    ADD CONSTRAINT invoice_items_pkey PRIMARY KEY (invoice_item_id);

--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (invoice_id);

--
-- Name: maintenance_windows maintenance_windows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_windows
    ADD CONSTRAINT maintenance_windows_pkey PRIMARY KEY (maintenance_id);

--
-- Name: media_assets media_assets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_assets
    ADD CONSTRAINT media_assets_pkey PRIMARY KEY (asset_id);

--
-- Name: navigation_items navigation_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.navigation_items
    ADD CONSTRAINT navigation_items_pkey PRIMARY KEY (nav_item_id);

--
-- Name: newsletter_subscribers newsletter_subscribers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.newsletter_subscribers
    ADD CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id);

--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);

--
-- Name: page_blocks page_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_blocks
    ADD CONSTRAINT page_blocks_pkey PRIMARY KEY (page_id, display_order);

--
-- Name: pages pages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pages
    ADD CONSTRAINT pages_pkey PRIMARY KEY (page_id);

--
-- Name: participants participants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participants
    ADD CONSTRAINT participants_pkey PRIMARY KEY (participant_id);

--
-- Name: redirects redirects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.redirects
    ADD CONSTRAINT redirects_pkey PRIMARY KEY (redirect_id);

--
-- Name: reservation_extras reservation_extras_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_extras
    ADD CONSTRAINT reservation_extras_pkey PRIMARY KEY (reservation_extra_id);

--
-- Name: reservation_repartitions reservation_repartitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_repartitions
    ADD CONSTRAINT reservation_repartitions_pkey PRIMARY KEY (repartition_id);

--
-- Name: reservation_tour_hebergements reservation_tour_hebergements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_tour_hebergements
    ADD CONSTRAINT reservation_tour_hebergements_pkey PRIMARY KEY (hebergement_id);

--
-- Name: reservation_tour_types reservation_tour_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_tour_types
    ADD CONSTRAINT reservation_tour_types_pkey PRIMARY KEY (reservation_tour_type_id);

--
-- Name: reservation_tours reservation_tours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_tours
    ADD CONSTRAINT reservation_tours_pkey PRIMARY KEY (reservation_tour_id);

--
-- Name: reservations reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (reservation_id);

--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (review_id);

--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);

--
-- Name: sources sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_pkey PRIMARY KEY (source_id);

--
-- Name: tour_highlights tour_highlights_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_highlights
    ADD CONSTRAINT tour_highlights_pkey PRIMARY KEY (tour_id, display_order);

--
-- Name: tour_included_items tour_included_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_included_items
    ADD CONSTRAINT tour_included_items_pkey PRIMARY KEY (tour_id, display_order);

--
-- Name: tour_not_included_items tour_not_included_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_not_included_items
    ADD CONSTRAINT tour_not_included_items_pkey PRIMARY KEY (tour_id, display_order);

--
-- Name: tour_photos tour_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_photos
    ADD CONSTRAINT tour_photos_pkey PRIMARY KEY (tour_id, display_order);

--
-- Name: tour_program_steps tour_program_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_program_steps
    ADD CONSTRAINT tour_program_steps_pkey PRIMARY KEY (tour_id, step_order);

--
-- Name: tour_type_highlights tour_type_highlights_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_highlights
    ADD CONSTRAINT tour_type_highlights_pkey PRIMARY KEY (tour_type_id, display_order);

--
-- Name: tour_type_included_items tour_type_included_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_included_items
    ADD CONSTRAINT tour_type_included_items_pkey PRIMARY KEY (tour_type_id, display_order);

--
-- Name: tour_type_not_included_items tour_type_not_included_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_not_included_items
    ADD CONSTRAINT tour_type_not_included_items_pkey PRIMARY KEY (tour_type_id, display_order);

--
-- Name: tour_type_photos tour_type_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_photos
    ADD CONSTRAINT tour_type_photos_pkey PRIMARY KEY (tour_type_id, display_order);

--
-- Name: tour_type_program_steps tour_type_program_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_program_steps
    ADD CONSTRAINT tour_type_program_steps_pkey PRIMARY KEY (tour_type_id, step_order);

--
-- Name: tour_type_translation_highlights tour_type_translation_highlights_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_translation_highlights
    ADD CONSTRAINT tour_type_translation_highlights_pkey PRIMARY KEY (tour_type_translation_id, display_order);

--
-- Name: tour_type_translation_included_items tour_type_translation_included_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_translation_included_items
    ADD CONSTRAINT tour_type_translation_included_items_pkey PRIMARY KEY (tour_type_translation_id, display_order);

--
-- Name: tour_type_translation_not_included_items tour_type_translation_not_included_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_translation_not_included_items
    ADD CONSTRAINT tour_type_translation_not_included_items_pkey PRIMARY KEY (tour_type_translation_id, display_order);

--
-- Name: tour_type_translation_program_steps tour_type_translation_program_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_translation_program_steps
    ADD CONSTRAINT tour_type_translation_program_steps_pkey PRIMARY KEY (tour_type_translation_id, step_order);

--
-- Name: tour_type_translations tour_type_translations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_translations
    ADD CONSTRAINT tour_type_translations_pkey PRIMARY KEY (tour_type_translation_id);

--
-- Name: tour_types tour_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_types
    ADD CONSTRAINT tour_types_pkey PRIMARY KEY (tour_type_id);

--
-- Name: tours tours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tours
    ADD CONSTRAINT tours_pkey PRIMARY KEY (tour_id);

--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id);

--
-- Name: tour_type_translations uk1djssv9jk474abp73mquxqyq7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_translations
    ADD CONSTRAINT uk1djssv9jk474abp73mquxqyq7 UNIQUE (tour_type_id, locale);

--
-- Name: transactions uk3w93192dhkdixcb3xncuf84pj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT uk3w93192dhkdixcb3xncuf84pj UNIQUE (transaction_number);

--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

--
-- Name: redirects uk7yhj77wlm61y7acfjd69428gg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.redirects
    ADD CONSTRAINT uk7yhj77wlm61y7acfjd69428gg UNIQUE (from_path);

--
-- Name: maintenance_windows uk8mfh81k0w3xhylrhwyn2ajqpp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_windows
    ADD CONSTRAINT uk8mfh81k0w3xhylrhwyn2ajqpp UNIQUE (path);

--
-- Name: tour_types uk9dw4i93sndvpqjtppute1x86x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_types
    ADD CONSTRAINT uk9dw4i93sndvpqjtppute1x86x UNIQUE (slug);

--
-- Name: invoices uk_invoice_number_type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT uk_invoice_number_type UNIQUE (invoice_number, invoice_type);

--
-- Name: reviews uk_review_user_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT uk_review_user_product UNIQUE (user_id, product_id, product_type);

--
-- Name: role_permissions uk_role_resource; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT uk_role_resource UNIQUE (role, resource);

--
-- Name: media_assets ukdrpw2245p1msggh0iq2po8ag1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_assets
    ADD CONSTRAINT ukdrpw2245p1msggh0iq2po8ag1 UNIQUE (stored_filename);

--
-- Name: account_action_tokens ukeaedwqsp35plrhxpu3lvx0gd1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_action_tokens
    ADD CONSTRAINT ukeaedwqsp35plrhxpu3lvx0gd1 UNIQUE (token);

--
-- Name: document_sequences ukjcggeypct97402emk0wc0qbfi; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_sequences
    ADD CONSTRAINT ukjcggeypct97402emk0wc0qbfi UNIQUE (type, year);

--
-- Name: availability_blocks ukke399n6lijjlgf9q1ms95g9p0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.availability_blocks
    ADD CONSTRAINT ukke399n6lijjlgf9q1ms95g9p0 UNIQUE (tour_type_id, date);

--
-- Name: pages ukmhs3k4hfx8l362xmd5iexwnxg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pages
    ADD CONSTRAINT ukmhs3k4hfx8l362xmd5iexwnxg UNIQUE (slug, locale, company_type);

--
-- Name: tours uko61q2fu99qfi7hvheq6lnntim; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tours
    ADD CONSTRAINT uko61q2fu99qfi7hvheq6lnntim UNIQUE (slug);

--
-- Name: extras ukotsklgf814gypsgvqp5cv8ma3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extras
    ADD CONSTRAINT ukotsklgf814gypsgvqp5cv8ma3 UNIQUE (slug);

--
-- Name: newsletter_subscribers ukqqdefkuupml4s7190ettcy6jy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.newsletter_subscribers
    ADD CONSTRAINT ukqqdefkuupml4s7190ettcy6jy UNIQUE (email);

--
-- Name: extra_translations ukqrfww5m8cgv2aufc1nqrdtg3d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_translations
    ADD CONSTRAINT ukqrfww5m8cgv2aufc1nqrdtg3d UNIQUE (extra_id, locale);

--
-- Name: user_product_remises user_product_remises_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_product_remises
    ADD CONSTRAINT user_product_remises_pkey PRIMARY KEY (id);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

--
-- Name: tour_type_translation_highlights fk1bfee3gagaicpl7af6hxdoyk9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_translation_highlights
    ADD CONSTRAINT fk1bfee3gagaicpl7af6hxdoyk9 FOREIGN KEY (tour_type_translation_id) REFERENCES public.tour_type_translations(tour_type_translation_id);

--
-- Name: page_blocks fk1h8h6c6er5xjar8vykw56vofe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_blocks
    ADD CONSTRAINT fk1h8h6c6er5xjar8vykw56vofe FOREIGN KEY (page_id) REFERENCES public.pages(page_id);

--
-- Name: tour_type_highlights fk3t72klcqo378l1ddbgts7bs07; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_highlights
    ADD CONSTRAINT fk3t72klcqo378l1ddbgts7bs07 FOREIGN KEY (tour_type_id) REFERENCES public.tour_types(tour_type_id);

--
-- Name: invoice_items fk46ae0lhu1oqs7cv91fn6y9n7w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_items
    ADD CONSTRAINT fk46ae0lhu1oqs7cv91fn6y9n7w FOREIGN KEY (invoice_id) REFERENCES public.invoices(invoice_id);

--
-- Name: tour_type_included_items fk645k2gj1lvtgj7x22qgfdqsp6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_included_items
    ADD CONSTRAINT fk645k2gj1lvtgj7x22qgfdqsp6 FOREIGN KEY (tour_type_id) REFERENCES public.tour_types(tour_type_id);

--
-- Name: transactions fk6fbx9j4v0gs6oiwwh2i5o5qh8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk6fbx9j4v0gs6oiwwh2i5o5qh8 FOREIGN KEY (reservation_id) REFERENCES public.reservations(reservation_id);

--
-- Name: extra_translation_program_steps fk6fcejw62mbwtchewy7mr41r3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_translation_program_steps
    ADD CONSTRAINT fk6fcejw62mbwtchewy7mr41r3 FOREIGN KEY (extra_translation_id) REFERENCES public.extra_translations(extra_translation_id);

--
-- Name: chauffeurs fk7u85nqhp5cc4hh6p713821vwv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chauffeurs
    ADD CONSTRAINT fk7u85nqhp5cc4hh6p713821vwv FOREIGN KEY (reservation_id) REFERENCES public.reservations(reservation_id);

--
-- Name: extra_highlights fk7xrelrtjxy2adgv2gmwd4je9e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_highlights
    ADD CONSTRAINT fk7xrelrtjxy2adgv2gmwd4je9e FOREIGN KEY (extra_id) REFERENCES public.extras(extra_id);

--
-- Name: extra_photos fk8h3s8sl18dp54tcg25aiqixqe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_photos
    ADD CONSTRAINT fk8h3s8sl18dp54tcg25aiqixqe FOREIGN KEY (extra_id) REFERENCES public.extras(extra_id);

--
-- Name: reservation_extras fk925nv4uvhjru0vagajntwurin; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_extras
    ADD CONSTRAINT fk925nv4uvhjru0vagajntwurin FOREIGN KEY (reservation_id) REFERENCES public.reservations(reservation_id);

--
-- Name: tour_languages fk981nd95ebruohnnc18ckkvy48; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_languages
    ADD CONSTRAINT fk981nd95ebruohnnc18ckkvy48 FOREIGN KEY (tour_id) REFERENCES public.tours(tour_id);

--
-- Name: extra_not_included_items fk9grn3b867nxv4gqt456i1artu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_not_included_items
    ADD CONSTRAINT fk9grn3b867nxv4gqt456i1artu FOREIGN KEY (extra_id) REFERENCES public.extras(extra_id);

--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(user_id);

--
-- Name: account_action_tokens fka12wi8vroril0ufrdaphna0hr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_action_tokens
    ADD CONSTRAINT fka12wi8vroril0ufrdaphna0hr FOREIGN KEY (user_id) REFERENCES public.users(user_id);

--
-- Name: reservation_repartitions fka214eoynjg7ii1bxv0nof5osv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_repartitions
    ADD CONSTRAINT fka214eoynjg7ii1bxv0nof5osv FOREIGN KEY (reservation_tour_type_id) REFERENCES public.reservation_tour_types(reservation_tour_type_id);

--
-- Name: tour_type_not_included_items fka55ln3jrrt0fx5rg261krqxwx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_not_included_items
    ADD CONSTRAINT fka55ln3jrrt0fx5rg261krqxwx FOREIGN KEY (tour_type_id) REFERENCES public.tour_types(tour_type_id);

--
-- Name: tour_highlights fkaq3ia4klpirbb018ll28wvx9r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_highlights
    ADD CONSTRAINT fkaq3ia4klpirbb018ll28wvx9r FOREIGN KEY (tour_id) REFERENCES public.tours(tour_id);

--
-- Name: reservations fkb5g9io5h54iwl2inkno50ppln; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fkb5g9io5h54iwl2inkno50ppln FOREIGN KEY (user_id) REFERENCES public.users(user_id);

--
-- Name: tour_not_included_items fkbfuffikxypvcmb3dvc9p95kao; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_not_included_items
    ADD CONSTRAINT fkbfuffikxypvcmb3dvc9p95kao FOREIGN KEY (tour_id) REFERENCES public.tours(tour_id);

--
-- Name: invoices fkbwr4d4vyqf2bkoetxtt8j9dx7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fkbwr4d4vyqf2bkoetxtt8j9dx7 FOREIGN KEY (user_id) REFERENCES public.users(user_id);

--
-- Name: reviews fkcgy7qjc1r99dp117y9en6lxye; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id) REFERENCES public.users(user_id);

--
-- Name: tour_photos fkcjp3xs5qvf0433y521jyrgvhv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_photos
    ADD CONSTRAINT fkcjp3xs5qvf0433y521jyrgvhv FOREIGN KEY (tour_id) REFERENCES public.tours(tour_id);

--
-- Name: extra_program_steps fkcqrm1b0ssralheuwxjkadguk7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_program_steps
    ADD CONSTRAINT fkcqrm1b0ssralheuwxjkadguk7 FOREIGN KEY (extra_id) REFERENCES public.extras(extra_id);

--
-- Name: extra_included_items fkcr76c6p7i0mmcya9y5br0x054; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_included_items
    ADD CONSTRAINT fkcr76c6p7i0mmcya9y5br0x054 FOREIGN KEY (extra_id) REFERENCES public.extras(extra_id);

--
-- Name: participants fkctdl6ivsl0oth6sjdq0chy2o9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participants
    ADD CONSTRAINT fkctdl6ivsl0oth6sjdq0chy2o9 FOREIGN KEY (reservation_id) REFERENCES public.reservations(reservation_id);

--
-- Name: reservation_repartitions fkd6ink842eedo67sknixwh1ebq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_repartitions
    ADD CONSTRAINT fkd6ink842eedo67sknixwh1ebq FOREIGN KEY (reservation_id) REFERENCES public.reservations(reservation_id);

--
-- Name: user_product_remises fkdumlm4y069h00556ngskk1wwj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_product_remises
    ADD CONSTRAINT fkdumlm4y069h00556ngskk1wwj FOREIGN KEY (user_id) REFERENCES public.users(user_id);

--
-- Name: tour_type_translation_program_steps fkga5o3bkcqq56dmkr16n1dv9cp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_translation_program_steps
    ADD CONSTRAINT fkga5o3bkcqq56dmkr16n1dv9cp FOREIGN KEY (tour_type_translation_id) REFERENCES public.tour_type_translations(tour_type_translation_id);

--
-- Name: tour_type_translations fkgi9la5ob4pnlyeks3c7n3r9q2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_translations
    ADD CONSTRAINT fkgi9la5ob4pnlyeks3c7n3r9q2 FOREIGN KEY (tour_type_id) REFERENCES public.tour_types(tour_type_id);

--
-- Name: reservations fkh1ojsn9jsor0h48tohp2nmmnn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fkh1ojsn9jsor0h48tohp2nmmnn FOREIGN KEY (source_ref_id) REFERENCES public.sources(source_id);

--
-- Name: extra_translation_included_items fkhbyd740pkgoic5c4af8ycoo5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_translation_included_items
    ADD CONSTRAINT fkhbyd740pkgoic5c4af8ycoo5 FOREIGN KEY (extra_translation_id) REFERENCES public.extra_translations(extra_translation_id);

--
-- Name: extra_translation_not_included_items fkhovr6kfk64trvo9pgt8bvx9qu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_translation_not_included_items
    ADD CONSTRAINT fkhovr6kfk64trvo9pgt8bvx9qu FOREIGN KEY (extra_translation_id) REFERENCES public.extra_translations(extra_translation_id);

--
-- Name: reservation_repartitions fkj1k55hr52a9i14tnvdyn2ahgd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_repartitions
    ADD CONSTRAINT fkj1k55hr52a9i14tnvdyn2ahgd FOREIGN KEY (reservation_tour_hebergement_id) REFERENCES public.reservation_tour_hebergements(hebergement_id);

--
-- Name: reservation_tours fkjm398yx0yok8k82398siin3ra; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_tours
    ADD CONSTRAINT fkjm398yx0yok8k82398siin3ra FOREIGN KEY (reservation_id) REFERENCES public.reservations(reservation_id);

--
-- Name: invoices fkkga8j6hh54xf5hl3qiovlsa4l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fkkga8j6hh54xf5hl3qiovlsa4l FOREIGN KEY (reservation_id) REFERENCES public.reservations(reservation_id);

--
-- Name: extra_languages fkkqc7sn3noe9ufqxqoxcxh38j7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_languages
    ADD CONSTRAINT fkkqc7sn3noe9ufqxqoxcxh38j7 FOREIGN KEY (extra_id) REFERENCES public.extras(extra_id);

--
-- Name: tour_type_translation_not_included_items fkkyrvcd62ditg28hxwgbxjf4vd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_translation_not_included_items
    ADD CONSTRAINT fkkyrvcd62ditg28hxwgbxjf4vd FOREIGN KEY (tour_type_translation_id) REFERENCES public.tour_type_translations(tour_type_translation_id);

--
-- Name: guides fklac4fjjviglwuan3f70v24cj2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guides
    ADD CONSTRAINT fklac4fjjviglwuan3f70v24cj2 FOREIGN KEY (reservation_id) REFERENCES public.reservations(reservation_id);

--
-- Name: tour_included_items fklwpowkjuy9v76c3stt09whu66; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_included_items
    ADD CONSTRAINT fklwpowkjuy9v76c3stt09whu66 FOREIGN KEY (tour_id) REFERENCES public.tours(tour_id);

--
-- Name: transactions fkm5goxujeqrwf774cgr0r04553; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkm5goxujeqrwf774cgr0r04553 FOREIGN KEY (invoice_id) REFERENCES public.invoices(invoice_id);

--
-- Name: reservation_tour_types fkmhq9dc7uv6itb9uvy0v922kev; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_tour_types
    ADD CONSTRAINT fkmhq9dc7uv6itb9uvy0v922kev FOREIGN KEY (reservation_id) REFERENCES public.reservations(reservation_id);

--
-- Name: tour_type_photos fkn29s3mf582smb11df3gyq5own; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_photos
    ADD CONSTRAINT fkn29s3mf582smb11df3gyq5own FOREIGN KEY (tour_type_id) REFERENCES public.tour_types(tour_type_id);

--
-- Name: tour_type_languages fkn2r9xhfn6ylalcokvr9ai27si; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_languages
    ADD CONSTRAINT fkn2r9xhfn6ylalcokvr9ai27si FOREIGN KEY (tour_type_id) REFERENCES public.tour_types(tour_type_id);

--
-- Name: extra_translations fkpkvgt4nbw4wlhtjtppu87iuh0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_translations
    ADD CONSTRAINT fkpkvgt4nbw4wlhtjtppu87iuh0 FOREIGN KEY (extra_id) REFERENCES public.extras(extra_id);

--
-- Name: tour_type_translation_included_items fkpt10hyi8j180ap8avfe3ns2y5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_translation_included_items
    ADD CONSTRAINT fkpt10hyi8j180ap8avfe3ns2y5 FOREIGN KEY (tour_type_translation_id) REFERENCES public.tour_type_translations(tour_type_translation_id);

--
-- Name: reservation_tour_hebergements fkskgrbubuh9om95a53giw49sh4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation_tour_hebergements
    ADD CONSTRAINT fkskgrbubuh9om95a53giw49sh4 FOREIGN KEY (reservation_tour_id) REFERENCES public.reservation_tours(reservation_tour_id);

--
-- Name: tour_type_program_steps fksrmg90blr69wu0c8t52h4kaj6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_type_program_steps
    ADD CONSTRAINT fksrmg90blr69wu0c8t52h4kaj6 FOREIGN KEY (tour_type_id) REFERENCES public.tour_types(tour_type_id);

--
-- Name: tour_program_steps fkstmxfddvjuao2dd492nhbmvbm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tour_program_steps
    ADD CONSTRAINT fkstmxfddvjuao2dd492nhbmvbm FOREIGN KEY (tour_id) REFERENCES public.tours(tour_id);

--
-- Name: availability_blocks fkt7rmy2awqsq5qx57dqwm4pxil; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.availability_blocks
    ADD CONSTRAINT fkt7rmy2awqsq5qx57dqwm4pxil FOREIGN KEY (tour_type_id) REFERENCES public.tour_types(tour_type_id);

--
-- Name: extra_translation_highlights fktp37mybx4nt7v4itjn5iy91eo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.extra_translation_highlights
    ADD CONSTRAINT fktp37mybx4nt7v4itjn5iy91eo FOREIGN KEY (extra_translation_id) REFERENCES public.extra_translations(extra_translation_id);

--
--
